# flume.conf

agent.sources = django-source
agent.channels = memory-channel
agent.sinks = hive-sink

# Source configuration
#agent.sources.django-source.type = netcat
agent.sources.django-source.type=exec
agent.sources.django-source.command=tail -F /public/home/medical_2324/Medical_LLM/logs/django.log
#agent.sources.django-source.bind = localhost
#agent.sources.django-source.port = 4444
agent.sources.django-source.channels = memory-channel
# Adjust the path to match your Django log file

# Channel configuration
agent.channels.memory-channel.type = memory

# Sink configuration
agent.sinks.hive-sink.type = hdfs
agent.sinks.hive-sink.channel = memory-channel
agent.sinks.hive-sink.hdfs.path=/django
agent.sinks.hive-sink.hdfs.filePrefix = django
agent.sinks.hive-sink.hdfs.fileSuffix = .log
agent.sinks.hive-sink.hdfs.fileType = DataStream
agent.sinks.hive-sink.hdfs.writeFormat = Text
#agent.sinks.hive-sink.serializer.serdeSeparator = '\t'
#agent.sinks.hive-sink.serializer.fieldnames = type,executor,content,add_time

# Replace your-hive-metastore-uri, your_database_name, and your_table_name with the actual values

agent.channels.memory-channel.capacity=10000
agent.channels.memory-channel.transactionCapacity=1000
agent.sinks.hive-sink.batchSize = 5
agent.sinks.hive-sink.hdfs.rollSize=10485760
agent.sinks.hive-sink.hdfs.rollInterval = 0
agent.sinks.hive-sink.hdfs.rollCount = 0
agent.sinks.hive-sink.hdfs.minBlockReplicas=1
agent.sources.django-source.logAllEvents = true
agent.sinks.hive-sink.batchTimeout = 5000
